apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: devops-training
spec:
  selector:
    matchLabels:
      app: api
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: petstore-api
        image: ghcr.io/pitipume/devops-java-example:c8ad491ec62de671e36672f52950fd3bb60682f0
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: api.service.port
